language: node_js
node_js:
- '6'
before_install:
- npm i npm-cli-login -g
- echo "NPM_USER=${NPM_USER}"
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
install:
- npm install
script:
- ./ci/build.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
- ./ci/travis/push_sugos_index.js
env:
  secure: "PeD/YDt8R5/ORNHEPbgyznE/7TAxWQkWDqS5B+pZYO6mjacGIn0J2VRvSJM/shbq549YgFGrzjdE6/YOMuYk8FM+qoGipwhqH1e8mpfXc0dF/PQLpbhkHBphm8VKstFR0FWtoRTw1vBOzzPxpWRQbvcDK8PhciKHjbUeaEfgjd6x+0unTrmaqPGd64iVWwTKVbJOO3xp8RbHuFWloH8eYTDz+zYRGAgMSEftqBINmunxvqS3zUqQ62P1KJf7e7gPvOecgTquP1H1LT5r573CkPUPj3LlogA8Ld59kOsd4COe/gJsedYD2GvoGAw70Gp0PZwtMyIRjOMbAQznvboSLWR0r8+ZUjCUGVcRiTrNinVnHkHVnRrkPbsRm1ypFIcDInOTDN0zhNkY66q3Af/H1GcM98pdOCdUSbDGcrYh4zn+5ErlD6XYgiYdsN7LDyYoTitftl9KcfE7mXm7LI/2XmdG9EcbQNvOXS40fyPtVT3vp/I/joKey6anU3v31Xj0MWE1oVhy/yGBSX3E62hhDWAODCdJzhBY8B0+RMm4A+ZLAn3XsekSsr7tdyZnhhBWVOXpfvGkIUREYtr0ZBpEZhJsGqD2AzaQj91NWPWKMoBIr8uXMNZewg1gy9C5hRTe1VzXvkH08r6sm2NBY5xBxHwEWAU4Le1lxDHTihVZpM8="
