language: node_js
node_js:
- '6'
before_install:
- npm i npm-cli-login -g
- echo "NPM_USER=${NPM_USER}"
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
install:
- npm install
script:
- ./ci/build.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
- ./ci/travis/push_sugos_index.js

env:
  secure: "rZP5NVBpSmWPS5V2V4jZH3Pw/2wiCi0/0+jLqTNGosMqtNkkqCShiM4UvDSU4KFjzUTMVzmxI3ViLBa2hz2SR1uommbMSt8PkiyKYbah0GDhdkA2qMikx0BQJc8drvF9x7EdBIaJ4ODYvZ4Qvx3D/Gh9y5oIRPD9gpyegngNkcSGjlbF8Jix3VmqKJN8LqWDecbz8YP4eXpv+Bxq1fp1hOGx42V8yaEKPyBuz23wohKu5EqBFaqxAtp+1bD8C9Q/v0WpMtldMtLeOPJgM1cYdlXVkveLX2/4eLgJnxtheNHTOTKdFgCJe3neaJVeySgQlkPLA/nnN13sW9aQyrPNXw/w6b7T/Gsbq23ejnAfltTP2A8zvw7Dl/hP06b4OnfOMLpAlbxJtlb2+Iwd143H0kKDJbX8UKdt8HKnEgWLIc9AhmB0BH40oOaD8egpiOmtw66tCKBX+a4g81OW4uI6gT+T61aEbh0j120PpO9C0xfmjuG+cysywfoA4eNm+1cIzDdn5+y6jsA5WG98DkjIbt/tUHUadCbimC8G/deG+qeoSgDn2q0bQXHhObGWBMlDEuvCyQve1Gk25zUGbmj8oMcMg0zZb5zbnS9cxBfVzkiKIkXGsy3UYOnhhWaazp5xAS3LntyLrZWzipHj11+memkCUo10el+P12vPzBOS8uA="
